# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Row Sums
#'
#' @param x an array of two or more dimensions, containing numeric, complex, integer or logical values, or a numeric data frame.
#'
#' @export
rowSumsC <- function(x) {
    .Call(`_mylm_rowSumsC`, x)
}

#' Matrix multiplication
#'
#' @param a First matrix
#' @param b Second matrix
#'
#' @export
matrix_multiply_c <- function(a, b) {
    .Call(`_mylm_matrix_multiply_c`, a, b)
}

